### PR TITLE
Simplify checking out latest release

### PR DESCRIPTION
**Pull request by shiruken**
Use GitHub action to check out repository and swap to latest tag rather than downloading archive

Successful run can be seen [here](https://github.com/shiruken/mastodon_get_replies/actions/runs/4500950076/jobs/7920730274)

### CODE REVIEW

**Comment by nanos** [comment]
Thanks for that @shiruken 

but won’t that try to push a commit to the `nanos/mastodon_get_replies` repo in the keep alive step, rather than in your own clone?

**Comment by nanos** [comment]
Thanks for that! Are you able to share a log, to confirm the checkout is actually working?

wondering because the directory won’t be empty.

**Comment by shiruken** [comment]
Yeah it seems to have run properly [here](https://github.com/shiruken/mastodon_get_replies/actions/runs/4504198702/jobs/7928368884)

**Comment by nanos** [comment]
Great stuff, thanks!

I will merge that with the next release.

**Pull request merged**
