### PR TITLE
updates github action to increment version

### PR DESCRIPTION
**Pull request by bdmorin**
```
sed  -i -E 's/VERSION = ".*?"/VERSION = '$VERSION'/g' find_posts.py
```

comments out debugging step

### CODE REVIEW

**Comment by nanos** [comment]
Thanks for that, I truly appreciate it!

however, this won't actually work more than once.

E.g. it'll replace the line `VERSION = "1.7.1"` with `VERSION = '1.7.2'` (single quotes with double quotes) which then won't match the patter on subsequent executions.

Also, I'd quite like to keep the more restrictive pattern to avoid accidentally replacing things that shouldn't be replaced (it's particularly the `/g` flag on there that makes me very nervous).

**Comment by bdmorin** [comment]
oh.. jeez. I forgot to replace the $github.ref_name

**Comment by bdmorin** [comment]
Ah, yea I see your point.

```sh
sed  -i -E 's/VERSION = ".*?"/VERSION = "'$VERSION'"/g' find_posts.py
```

That fixes the quote issue. 
when I debugged the run, the version number was missing entirely, that's why i didn't match semver. You can put the match back in if VERSION is prepopulated.

**Comment by nanos** [comment]
thanks again @bdmorin

**Pull request merged**
